# Generated by Django 3.2.6 on 2021-08-10 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0006_auto_20210809_0909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='on',
        ),
        migrations.AddField(
            model_name='comment',
            name='onComment',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_comments', to='BlogApp.comment'),
        ),
        migrations.AddField(
            model_name='comment',
            name='onPost',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to='BlogApp.post'),
        ),
    ]
